export { PlateformeHome } from "./pages/plateforme-home"
export { PackageVersion } from "./components/package-version"
export { CoquilleOto } from "./components/coquille-oto"
export { NavigateurDArbre, NavigateurDArbreChargement } from "./arbre/navigateur-d-arbre"
export type { NoeudDArbre } from "./arbre/types"
export { EcranDAuthentification } from "./authentification/ecran-d-authentification"
export { IlotDAuthentification } from "./authentification/ilot-d-authentification"
export { AucuneOrganisation, AucuneOrganisationChargement } from "./identite/aucune-organisation"
export type { ResultatAucuneOrganisation } from "./identite/aucune-organisation"
export { InviterQuelquUn } from "./invitations/inviter-quelqu-un"
export { EcranMarque, EcranMarqueChargement } from "./marque/ecran-marque"
export { LogoDOrganisation } from "./marque/logo-d-organisation"
export type { DonneesDeMarque, MarqueDOrganisation, ResultatDeMarque } from "./marque/types"
export { Consentement, ConsentementChargement } from "./oauth/consentement"
export type { DemandeDeConsentement, ErreurDeDecision, OrganisationDeLaDemande } from "./oauth/types"
export { EcranEquipes, EcranEquipesChargement } from "./equipes/ecran-equipes"
export type { EcranEquipesProps } from "./equipes/ecran-equipes"
export type { Moi } from "./equipes/types"
export { ReglesDuNoeud } from "./equipes/regles-du-noeud"
export { AccesPlateforme } from "./equipes/acces-plateforme"
export { ActionPlateforme } from "./components/action-plateforme"
export { ContexteDeRafraichissement, useRafraichir } from "./hote/rafraichir"
export { resultatDe } from "./api/resultat"
export { dateLisible } from "./format/dates"
export { EcranConnexion, EcranConnexionChargement } from "./connexion/ecran-connexion"
export type { AdresseDeConnexion, DerniereConnexion, ExempleDePrompt } from "./connexion/types"
export { EcranDuJournal, EcranDuJournalChargement } from "./journal/ecran-du-journal"
export type { EcranDuJournalProps, ParametresDuJournal } from "./journal/ecran-du-journal"
export { reserveAuxAdministrateurs } from "./admin/textes"
export { EcranUsage, EcranUsageChargement } from "./admin/usage/ecran-usage"
export type { EcranUsageProps } from "./admin/usage/ecran-usage"
export { EcranRetours, EcranRetoursChargement } from "./admin/retours/ecran-retours"
export type { EcranRetoursProps } from "./admin/retours/ecran-retours"
export { EcranDeNoeud, EcranDeNoeudChargement } from "./noeud/ecran-de-noeud"
export { ErreurDeLecture } from "./components/erreur-de-lecture"
export { EcranOrganisation, EcranOrganisationChargement } from "./admin/organisation/ecran-organisation"
export type { EcranOrganisationProps } from "./admin/organisation/ecran-organisation"
export { EcranConnecteurs, EcranConnecteursChargement } from "./admin/connecteurs/ecran-connecteurs"
export type { DonneesDesConnecteurs, EcranConnecteursProps } from "./admin/connecteurs/ecran-connecteurs"
export { EcranDrapeaux, EcranDrapeauxChargement } from "./admin/drapeaux/ecran-drapeaux"
export type { EcranDrapeauxProps } from "./admin/drapeaux/ecran-drapeaux"
export { AccesPlateformeChargement } from "./admin/ilot"
// E07-S03 : la grille, la file et la revue d'un tableau ; les blocs `reference` rendus en place.
export { EcranDeTableauChargement, TableauDuNoeud } from "./tableau/tableau-du-noeud"
export type { TableauDuNoeudProps } from "./tableau/tableau-du-noeud"
export { VueDeTableau } from "./tableau/vue-de-tableau"
export { CarteDeNoeud } from "./tableau/carte-de-noeud"
export { referencesRendues } from "./tableau/references-rendues"
export { adresseDesReglages, reglagesDepuisLAdresse } from "./tableau/adresse"
export { MESSAGES_DU_TABLEAU } from "./tableau/libelles"
export type { Reglages, ReglagesLus } from "./tableau/adresse"
export { blocsAffiches } from "./noeud/ecran-de-noeud"
export { ListeDesProcedures, ListeDesProceduresChargement } from "./procedure/liste-des-procedures"
// Obsolète (M59, fiche D104) : ne rend plus rien, gardé pour les hôtes qui le montent (ADR-006).
export { ProcedureDuNoeud } from "./procedure/procedure-du-noeud"
export { AnnexesDuContexte } from "./contexte/annexes-du-contexte"
export { genreDuNoeud } from "./noeud/libelles"
export { FaviconDuTheme } from "./components/favicon-du-theme"
// E05-S09 (partie a) : la coque unique, le rail d'oto-frontend, entier ou par morceaux, et les primitives
// du design system qui le composent (ADR-008 point 7) ; ce que l'hôte lui prête (`ContexteDeLHote`).
export { RailApplication } from "./coque/rail-application"
export type { RailApplicationProps } from "./coque/rail-application"
export { EntrepriseDuRail } from "./coque/entreprise-du-rail"
export type { EntrepriseDuRailProps } from "./coque/entreprise-du-rail"
export { RechercheDuRail } from "./coque/recherche-du-rail"
export type { RechercheDuRailProps } from "./coque/recherche-du-rail"
export { SectionsDuRail } from "./coque/sections-du-rail"
export type { SectionsDuRailProps } from "./coque/sections-du-rail"
export { PiedDuRail } from "./coque/pied-du-rail"
export type { PiedDuRailProps } from "./coque/pied-du-rail"
export type { AdressesDuRail, DonneesDuRail } from "./coque/types"
export { ContexteDeLHote } from "./hote/navigation"
export type { Hote, LienDuRail } from "./hote/navigation"
export { Content, Desk, Rail, RailItem } from "./ds/react/layout"
export { RailSection } from "./ds/react/rail"
export { RailTree } from "./ds/react/rail-tree"
export type { RailTreeNode } from "./ds/react/rail-tree"
export { DropdownMenu } from "./ds/react/overlays"
export type { MenuItem } from "./ds/react/overlays"
// E05-S09 (partie b) : l'accueil d'oto-frontend, sur les données du paquet que la page de l'hôte lit.
export { EcranDAccueil, EcranDAccueilChargement } from "./accueil/ecran-accueil"
export type { EcranDAccueilProps } from "./accueil/ecran-accueil"
export type { DonneesDeLAccueil } from "./accueil/types"
// E11-S10 (lot e) : l'écran « Contexte », ce que lit l'assistant, lu par la page de l'hôte (`/context`).
export type { DonneesDuContexteServi } from "./contexte/contexte-servi"
export { EcranDuContexte, EcranDuContexteChargement } from "./contexte/ecran-du-contexte"
// E05-S09 (partie d3) : les primitives du design system que composent les formulaires d'authentification
// de l'hôte (connexion, mot de passe oublié, réinitialisation), rendus dans l'îlot du gabarit.
export { Alert, Button } from "./ds/react/primitives"
export { Field, Input } from "./ds/react/forms"
// E05-S09 (partie d2) : les écrans d'administration sur le design system ; « Accès plateforme » a son écran.
export { EcranAccesPlateforme } from "./admin/acces/ecran-acces-plateforme"
// E05-S10 (partie b2) : l'écran « Corbeille », ouvert par le pied du rail (AC-b11).
export { EcranDeLaCorbeille, EcranDeLaCorbeilleChargement } from "./corbeille/ecran-de-la-corbeille"
// E05-S10 (partie d, ADR-013) : la page publique d'un lien de partage, que l'hôte monte à `/p/<jeton>`, et son 404.
export { PAGE_PUBLIQUE, PagePublique, PagePubliqueIntrouvable } from "./public/page-publique"
export type { PagePubliqueProps } from "./public/page-publique"
// E05-S11 (lot a) : l'écran « Profil », que l'hôte monte à `/profil`.
export { EcranProfil, EcranProfilChargement } from "./profil/ecran-profil"
export type { EcranProfilProps } from "./profil/ecran-profil"
// E05-S11 (lot e) : le titre montré d'un Contexte, « Contexte · <section> », que la page de l'hôte met dans le `<title>` (AC-17).
export { titreDuContexte } from "./noeud/fil"
// E05-S12 (lot C, AC-7) : le chemin du Contexte d'une partie servie, servi ou non, que la page de l'hôte lit pour l'éditeur.
export { cheminDuContexte } from "./contexte/parties-du-contexte"
